os:
  - linux

dist: trusty
sudo: false

language: node_js
node_js:
  - node

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm ci;

script:
  - npm test;
  - if ([[ "$TRAVIS_TEST_RESULT" == "0" ]] && [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]); then
      jobFailed=0;

      jobFailed=$(npm start -- --branch=master --logsUrl=$TRAVIS_BUILD_WEB_URL && echo $jobFailed || echo 1);
      jobFailed=$(npm start -- --branch=stable --logsUrl=$TRAVIS_BUILD_WEB_URL && echo $jobFailed || echo 1);
      jobFailed=$(npm start -- --branch=rc --logsUrl=$TRAVIS_BUILD_WEB_URL && echo $jobFailed || echo 1);

      if ([[ "$jobFailed" == "1" ]]); then
        exit 1;
      fi
    fi
