os:
  - linux

dist: trusty
sudo: false

language: node_js
node_js:
  - node

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm ci;

script:
  - npm test;
  - if ([[ "$TRAVIS_TEST_RESULT" == "0" ]] && [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]); then
      npm start;
    fi
