name: Check for updates
on:
  workflow_dispatch: ~
  schedule:
    - cron: '42 8 * * *'
jobs:
  test:
    name: Test with node lts/* on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci;
      - run: npm test;
  check-for-updates:
    name: Check for updates
    needs: test
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_TOKEN___gkalpak_ngx_deps_upgrade: ${{ secrets.SECRET_GITHUB_ACCESS_TOKEN }}
      LOGS_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci;
      - run: npm run build;
      - name: Check next branch
        if: ${{ !cancelled() }}
        run: npm start -- --branch=next --logsUrl=$LOGS_URL;
      - name: Check stable branch
        if: ${{ !cancelled() }}
        run: npm start -- --branch=stable --logsUrl=$LOGS_URL;
      - name: Check RC branch
        if: ${{ !cancelled() }}
        run: npm start -- --branch=rc --logsUrl=$LOGS_URL;
