name: CI
on:
  - pull_request
  - push
jobs:
  test:
    name: Node lts/* on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci;
      - run: npm test;
